language: go
go:
  - 1.6
env:
  - secure: "OaHgerLmi9WIsCZNOm0LenezhwcUE8CcvQVuMYwz4tNXRwILjHdhHadgu1sr90h7YHnOs83fls3kfwLbDlX4cOBGerk+YG/UqBBZomnOJUXD/puTaepa7dGGKzyUBkXtjkggI0XLT8qQhQHVF0urR5Xfu34/JJNCYMgvKBP/btJWrr2JfummX1IDXiEhPn3YEb6fRILZmcDILYkg4dQFSNy1Gs3B+/v8Xvy8BKgEJwOxN+D2ETkC9WKoURjJfM6uPskc7ISF1ifZ8jq9P40BmNmx/NXKaz7/6QatVkx/Z3Wm4RLbSVyY/jqat7xyU/xX6lm8rbpzp7dAT+M9tY4exKH7I+2XeSIBDTxDHl0GCpsGv6bkFKYRXl2lWB++05Xpxc1+NU3svAn6Lljz3zuu7zzydLN76D9ndeCd7ikd/eF3C1viy41rSiQvfJnWImMt/XRgDxDov43HQ562aoTbrUnO5siIhp+Hy8HCC6tR2f6JxjTSoi95eGe1hcjcFJ2vElLBoCb/bkMwoCin4CyhPr8hpOPPG4BWsgh2XD3xXH3tSSngRUhgCGB15V20mLYNPXGnmNe0gWntsMG23UTtNGtMPP/vF8PQ05q/sJ2dmYWZf25XNF36O67zryhNReGloKi4AWNHLAzhYg0f+CbsY/mvW3oSDXZ9HrcdIvE9Bzs="
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
    - go test -v --race -covermode=count -coverprofile=coverage.out -benchmem -bench .
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
