language: go
go:
  - tip
services:
  - redis-server
env:
  - secure: "VtdBuBXt9uyY/u9FciEna9gqeZVdtYWFZyFk3cnbRt3HXTnZVs/m3JtRD0RIB+114HSxhokYs8sKp7ebBHX+3/EF80g+8csJPytCOT2P7a6IX9DyAshvo/bH1lg1PvRc+a2h0M6swK0tz+PfBx0i9lSq9yn9zZC3siSSzFmAzUJ3Fea13o6SCku0iS+3iv6fe2RoyAxMmAlpAir2WsGJr9iMHmBSzWD5gOrULD4qwioPUMoH9IJGniRTqwsPmoPxCRKO9eeuwGQnnW1Kr0NHvDu+nzqLAb+aMz1DdgfhYwHHI+Cbtj+sLn6mzC3xBRcnn0+EsFh0apCRPU0A2eV6NKUKOWjXYM+JkyxMSkrYr/TznnTcRpbmQG58sCWdl9wmQKa+qu1rKz9ZC2dj3MShpvQdBOGdpQPBPyRWjzyCBV1wsQmTbTTKNSbrwRRSayWkg0GUKB7RoSZWRfUoZkaxSR3zDlOIduLelrDAh3iH3aAdfHwO13N5EEkdsOOkmTXrBWd3rRAHoxD2vHXBLcr8mdldKmUBDUHMExpWqXMmKn6Gbz3daieaK6JiTvxgMSNEdqsxbtWCyxtsBp5zmV9XKGiWPc+QiLw+1cb7dsquVI8xLlrx6TUpjFUagIhS3W3aDbFqt8d0aXjwPWexLZ6yisPMcE+DRV9rBHNgm1c1wZ4="
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
    - go test -v --race -covermode=count -coverprofile=coverage.out -benchmem -bench .
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
